// config/base/section.js
export const base = {
  hero: {
    box: "default",
    eyebrow: "default",
    title: "default",
    first: "default",
    last: "default",
    heroCTA: "gap-4",
    subtitle: "default",
    desc: "default",
    rustBadge: "default",
    scrollHint: "default",
    stackBar: "default",
    stackItem: "default",
    stackIcon: "default",
    stackName: "default",
    right: "default",
    orb: "default",
    ring: "default",
    ring2: "default",
    termCardBack: "default",
    termCardBackLeft: "default",
    termCard: "default",
    topdots: "default",
    bottomdots: "default",
    centerDots: "default",
    planet: "default",
    planetRing: "default",
    orbit: "default",
  },
  navbar: {
    nav: "",
    displayText: "flex gap-10",
    NavLinkS: "flex justify-center items-center gap-4",
    displayImage: "hidden",
    menuEyeBrow: "text-xs3",
    menuLinkList: "default",
    logoImage: "w-full",
    menu: "mt-0",
    hamburger: "",
    logoTextImage: "w-10 h-10",
    logoText: "text-[clamp(1rem,calc(-2.012rem+6.275vw),2rem)]",
    navLink: "",
  },
  button: {
    primary: "px-6 py-3 rounded-xl",
    buttonCta: "py-[0.85rem]",
    buttonHero: "btnhero default",
    buttonOutline: "default",
  },
  section: {
    wrapper: "h-screen inline-table",
    default: "default",
    about: "default",
    client: "py-24 px-[48px]",
    skill: "default",
    tag: "default",
    icon: "default",
    text: "default",
    contact: "",
  },
  about: {
    left: "default",
    illustration: "default",
    corner: "default",
    badge: "default",
    labels: "default",
    val: "default",
    infoGrid: "default",
    infoItems: "default",
    infoBullet: "default",
    btnCTA: "default",
  },
  hiddens: "",
  standard: {
    eyebrow: "default",
    header: "section-text-header",
    cardtitle: "default",
    carddesc: "default",
    desc: "section-subtitle",
    icon: "text-[1.4rem] mb-4",
    stack: "",
    tag: "default",
    glassCardBox: "default",
    glassCardBoxDetail: "defaultDetail",
    glassCardEye: "default",
    glassCardCorner: "default",
    glassCardPeriod: "default",
    glassCardTitle: "default",
    glassCardDesc: "default",
    slide: "default",
    ferris: "default",
  },
  stats: {
    box: "default",
    items: "default",
    number: "default",
  },
  skill: {
    box: "default",
    techCard: "default",
  },
  project: {
    box: "default",
    boxdetail: "default-detail",
    name: "default",
    num: "default",
    numDot: "default",
    desc: "default",
    pcard: "default",
    pFeature: "default",
    pFeatureCard: "default",
    btnCTA: "default",
  },
  experience: {
    list: "default",
    items: "default",
    meta: "default",
    expdate: "default",
    company: "default",
    role: "default",
    desc: "default",
    divider: "",
  },
  terminal: {
    box: "default",
    bar: "default",
    dot: "default",
    username: "default",
    url: "default",
    body: "default",
    comments: "default",
    keys: "default",
    tString: "default",
  },
  services: {
    icon:"default",
    menugrid:"default",
    card:"default",
    herader:"default",
    num:"default",
    numIcon:"default",
    sTitle:"default",
    sDesc:"default",
    sLi:"default",
    sPrice:"default",
    sPriceLabel:"default",
    sPriceValue:"default",

  },
  term: {
    box: "default",
    icon: "default",
    terms: "default",
    items: "default",
  },
  clients: {
    box: "default",
    cc: "default",
    industry: "default",
    result: "default",
    label: "default",
    tcard: "default",
    quote: "default",
    avatar: "default",
    name: "default",
    role: "default",
    timeline: "default",
    tlItem: "default",
    tlDot: "default",
    tlContent: "default",
    tlLabel: "default",
  },
  contact: {
    big: "default",
    sub: "default",
    link: "default",
  },
  footer: {
    box: "default",
    label: "default",
  },
};
