// config/base/section.js
export const base = {
  hero: {
    box: "default",
    eyebrow: "default",
    title: "default",
    first: "default",
    last: "default",
    heroCTA: "gap-4",
    subtitle: "default",
    desc: "default",
    rustBadge: "default",
    scrollHint: "default",
    stackBar: "default",
    stackItem: "default",
    stackIcon: "default",
    stackName: "default",
    right: "default",
    orb: "default",
    ring: "default",
    ring2: "default",
    termCardBack: "default",
    termCard: "default",
    topdots: "default",
    bottomdots: "default",
    centerDots: "default",
    planet:"default",
    planetRing:"default",
    orbit:"default",
  },
  navbar: {
    nav: "",
    displayText: "flex gap-10",
    NavLinkS: "flex justify-center items-center gap-4",
    displayImage: "hidden",
    menuEyeBrow: "text-xs3",
    menuLinkList: "default",
    logoImage: "w-full",
    menu: "mt-0",
    hamburger: "",
    logoTextImage: "w-10 h-10",
    logoText: "text-[clamp(1rem,calc(-2.012rem+6.275vw),2rem)]",
    navLink: "",
  },
  button: {
    primary: "px-6 py-3 rounded-xl",
    buttonCta: "py-[0.85rem]",
    buttonHero: "btnhero default",
    buttonOutline: "default",
  },
  section: {
    wrapper: "h-screen inline-table",
    default: "default",
    about: "default",
    client: "py-24 px-[48px]",
    skill: "default",
    tag: "default",
    icon: "default",
    text: "default",
    contact: "",
  },
  about: {
    grid: "grid grid-cols-2 gap-3 items-start",
    photoWrap: "flex justify-center",
    photoFrame: "w-80 h-90",
    content: "",
    factBox: "grid gap-3 mt-8 grid-cols-2",
    factIcons: "text-rust font-mono text-[0.8rem] shrink-0 mt-[0.1rem]",
  },
  hiddens: "",
  standard: {
    eyebrow: "mono-label text-[0.75rem] text-teal tracking-[0.15em]",
    header: "section-text-header",
    cardtitle: "default",
    carddesc: "default",
    desc: "section-subtitle",
    icon: "text-[1.4rem] mb-4",
    stack: "",
    tag: "default",
    glassCardBox: "default",
    glassCardEye: "default",
    glassCardCorner: "default",
    glassCardPeriod: "default",
    glassCardTitle: "default",
    glassCardDesc: "default",
    slide: "default",
    ferris:"default"
  },
  stats: {
    box: "grid grid-cols-4 mb-2 gap-2 p-4",
    stat: "min-w-full borderR rounded-xl shadow-2xl p-4 overflow transition-surface hover:borderY",
    glow: "-bottom-5 -right-2.5 w-15 h-15 rounded-1/2 blur-[25px] opacity-[0.15] bg-teal",
    num: "font-mono text-[2.4rem] font-bold text-text leading-none mb-[0.4rem]",
    label: "text-sm text-muted uppercase tracking-[0.06em]",
  },
  skill: {
    box: "default",
    card: "",
  },
  experience: {
    list: "default",
    items: "default",
    meta: "default",
    expdate: "default",
    company: "default",
    role: "default",
    desc: "default",
    divider: "",
  },
  project: {
    num: "default",
    numDot: "default",
    desc: "default",
    stack: "default",
    corner: "default",
    pcard: "default",
    pFeature: "default",
    pFeatureCard: "default",
  },
  terminal: {
    box: "default",
    bar: "default",
    dot: "default",
    username: "default",
    url: "default",
    body: "default",
  },
  services: {
    box: "default",
    right: "default",
    menuright: "default",
    step: "default",
    num: "default",
    label: "default",
    desc: "default",
    menugrid: "default",
    flagwrapper: "default",
    flagarrow: "default",
  },
  term: {
    box: "default",
    icon: "default",
    terms: "default",
    items: "default",
  },
  clients: {
    box: "default",
    cc: "default",
    industry: "default",
    result: "default",
    label: "default",
    tcard: "default",
    quote: "default",
    avatar: "default",
    name: "default",
    role: "default",
    timeline: "default",
    tlItem: "default",
    tlDot: "default",
    tlContent: "default",
    tlLabel: "default",
  },
  contact: {
    big: "default",
    sub: "default",
    link: "default",
  },
  footer: {
    box: "default",
    label: "default",
  },
};
