export const mobileTall={
  hiddens:'hidden',
    hero: {
    box: "tallv1",
    eyebrow: "tallv1",
    title: "short",
    first: "tallv1",
    last: "tallv1",
    heroCTA: "heroCTAShort",
    subtitle: "short",
    desc: "default",
    scrollHint: "scrollHintTall",
    stackBar: "hidden",
    stackItem: "short",
    stackIcon: "hidden",
    stackName: "hidden",
    right: "hidden",
    orb: "hidden",
    ring: "hidden",
    ring2: "hidden",
    termCardBack: "hidden",
    termCardBackLeft: "hidden",
    termCard: "hidden",
    topdots: "hidden",
    bottomdots: "hidden",
    centerDots: "hidden",
    planet: "hidden",
    planetRing: "hidden",
    orbit: "hidden",
  },
  navbar: {
    nav: "",
    displayText: "flex gap-4",
    NavLinkS: "tall-v1",
    displayImage: "hidden",
    menuEyeBrow: "text-xs3",
    menuLinkList: "default",
    logoImage: "w-ful",
    menu: "mt-0",
    hamburger: "",
    logoTextImage: "w-10 h-10",
    logoText: "text-[clamp(1rem,calc(-2.012rem+6.275vw),2rem)]",
    navLink: "",
  },
    section: {
    wrapper: "h-screen inline-table",
    default: "short",
    about: "short",
    client: "py-24 px-[48px]",
    skill: "short",
    tag: "default",
    icon: "default",
    text: "default",
    contact: "",
  },
  about: {
    left: "short",
    illustration: "tallv1",
    corner: "default",
    top: "shorttop",
    bottom: "shortbottom",
    badge: "default",
    labels: "default",
    val: "default",
    infoGrid: "default",
    infoItems: "default",
    infoBullet: "default",
    btnCTA: "default",
    card: "short",
  },
  standard: {
    eyebrow: "default",
    header: "section-text-header-short",
    cardtitle: "default",
    carddesc: "default",
    desc: "section-subtitle",
    icon: "text-[1.4rem] mb-4",
    stack: "",
    tag: "default",
    glassCardBox: "default",
    glassCardBoxDetail: "defaultDetail",
    glassCardEye: "default",
    glassCardCorner: "default",
    glassCardPeriod: "default",
    glassCardTitle: "default",
    glassCardDesc: "default",
    slide: "compact",
    viewport: "compact",
    ferris: "short",
    timelineSubtitle: "compact",
    containercustom: "compact",
  },
  stats: {
    box: "short",
    items: "default",
    number: "default",
  },
  skill: {
    box: "tall",
    techCard: "tall",
  },
    project: {
    box: "tall",
    boxdetail: "default-detail",
    pFeature: "short",
    pFeatureCard: "short",
    portfoliolist: "",
  },
   services: {
    menugrid: "tall",
    sTitle: "short",
    sDesc: "short",
    sLi: "short",
    sPrice: "short",
    sPriceLabel: "short",
    sPriceValue: "short",
  },
}