export const mobileshort = {
    hero: {
    box: "short",
    eyebrow: "short",
    title: "short",
    first: "short",
    last: "short",
    heroCTA: "heroCTAShort",
    subtitle: "short",
    desc: "default",
    rustBadge: "default",
    scrollHint: "scrollHintShort",
    stackBar: "hidden",
    stackItem: "short",
    stackIcon: "hidden",
    stackName: "hidden",
    right: "hidden",
    orb: "hidden",
    ring: "hidden",
    ring2: "hidden",
    termCardBack: "hidden",
    termCardBackLeft: "hidden",
    termCard: "hidden",
    topdots: "hidden",
    bottomdots: "hidden",
    centerDots: "hidden",
    planet: "hidden",
    planetRing: "hidden",
    orbit: "hidden",
  },
  navbar: {
    nav: "compact",
    displayText: "hidden",
    NavLinkS: "flex justify-center items-center gap-4",
    displayImage: "static top-0",
    menuEyeBrow: "text-xs3",
    menuLinkList: "default",
    logoImage: "logo-image-short",
    menu: "mt-4",
    hamburger: " hamburger-short",
    logoTextImage: "w-10 h-10",
    logoText: "text-[clamp(1rem,calc(-2.012rem+6.275vw),2rem)]",
    navLink: "",
  },
  button: {
    primary: "px-6 py-3 rounded-xl",
    buttonCta: "py-[0.85rem]",
    buttonHero: "btnhero default",
    buttonOutline: "default",
  },
  section: {
    wrapper: "h-screen inline-table",
    default: "short",
    about: "short",
    client: "py-24 px-[48px]",
    skill: "short",
    tag: "default",
    icon: "default",
    text: "default",
    contact: "",
  },
  about: {
    left: "short",
    illustration: "short",
    corner: "default",
    top: "shorttop",
    bottom: "shortbottom",
    badge: "default",
    labels: "default",
    val: "default",
    infoGrid: "default",
    infoItems: "default",
    infoBullet: "default",
    btnCTA: "default",
    card: "short",
  },
  hiddens: "",
  standard: {
    eyebrow: "default",
    header: "section-text-header-short",
    cardtitle: "default",
    carddesc: "default",
    desc: "section-subtitle",
    icon: "text-[1.4rem] mb-4",
    stack: "",
    tag: "default",
    glassCardBox: "default",
    glassCardBoxDetail: "defaultDetail",
    glassCardEye: "default",
    glassCardCorner: "default",
    glassCardPeriod: "default",
    glassCardTitle: "default",
    glassCardDesc: "default",
    slide: "compact",
    viewport: "compact",
    ferris: "short",
    timelineSubtitle: "compact",
    containercustom: "compact",
  },
  stats: {
    box: "short",
    items: "default",
    number: "default",
  },
  skill: {
    box: "short",
    techCard: "short",
  },
  project: {
    box: "short",
    boxdetail: "default-detail",
    name: "default",
    num: "default",
    numDot: "default",
    desc: "default",
    pcard: "default",
    pFeature: "short",
    pFeatureCard: "short",
    btnCTA: "default",
    portfoliolist: "",
  },
  experience: {
    list: "default",
    items: "default",
    meta: "default",
    expdate: "default",
    company: "default",
    role: "default",
    desc: "default",
    divider: "",
  },
  terminal: {
    box: "default",
    bar: "default",
    dot: "default",
    username: "default",
    url: "default",
    body: "default",
    comments: "default",
    keys: "default",
    tString: "default",
  },
  services: {
    icon:"default",
    menugrid:"compact",
    card:"default",
    herader:"default",
    num:"default",
    numIcon:"default",
    sTitle:"short",
    sDesc:"short",
    sLi:"short",
    sPrice:"short",
    sPriceLabel:"short",
    sPriceValue:"short",

  },
  term: {
    box: "default",
    icon: "default",
    terms: "default",
    items: "default",
  },
  clients: {
    box: "default",
    cc: "default",
    industry: "default",
    result: "default",
    label: "default",
    tcard: "default",
    quote: "default",
    avatar: "default",
    name: "default",
    role: "default",
    timeline: "default",
    tlItem: "default",
    tlDot: "default",
    tlContent: "default",
    tlLabel: "default",
  },
  contact: {
    big: "default",
    sub: "default",
    link: "default",
  },
  footer: {
    box: "compact",
    label: "compact",
  },
};
