export const mobileshort = {
  navbar: {
    nav: "compact",
    displayText: "hidden",
    displayImage: "static top-0",
    logoImage: "logo-image-short",
    hamburger: " hamburger-short",
    heroCTA: "heroCTAShort",
    menu: "mt-4",
  },
  hero: {
    box: "hero-box-short",
    title: "hero-title-short",
    eyebrow: "hero-eyebrow-short",
    subtitle: "hero-subtitle-short",
    desc: "hero-desc-short ",
    rustBadge: "rust-badge-short",
    scrollHint: "scrollHintShort",
    right: "hidden",
    last: "compact",
    topdots: "compact",
    bottomdots: "compact",
    centerDots: "compact",
  },
  section: {
    wrapper: "wrapperShort",
    about: "sectionAboutShort",
    skill: "bg-surface sectionSkillShort",
    service: "compact",
    client: "compact px-2",
    contact: "flex! items-center! justify-center! flex-col!",
  },
  button: {
    buttonCta: "py-2",
    buttonHero: "btnhero compact",
  },
  about: {
    grid: "about-grid-short",
    photoWrap: "about-photo-wrap-short",
    photoFrame: "about-photo-frame-short",
    content: "mb-3",
    factBox: "about-facts-short",
    factIcons: "about-fact-icon-short",
  },
  standard: {
    eyebrow: "eyebrow-short",
    header: "title-short",
    cardtitle: "compact",
    carddesc: "compact",
    desc: "desc-short",
    icon: "short",
    stack: "short",
    slide: "compact",
  },
  stats: {
    box: "grid-cols-2 p-2 grid gap-2",
    stat: "min-w-full borderR rounded-xl shadow-2xl p-1 overflow transition-surface hover:borderY",
    glow: "-bottom-5 -right-2.5 w-15 h-10 rounded-1/2 blur-[25px] opacity-[0.15] bg-teal",
    num: "font-mono text-[clamp(0.75rem,calc(0.245rem+2.516vw),1rem)] font-bold text-text leading-none mb-[0.4rem]",
    label:
      "text-[clamp(0.75rem,calc(0.245rem+2.516vw),1rem)] text-muted uppercase tracking-[0.06em]",
  },
  skill: {
    box: "compact",
    card: "short beam beam-rust",
  },
  experience: {
    items: "compact",
    expdate: "short",
    company: "title-short",
    desc: "desc-short",
    divider: "my-1",
  },
  project: {
    num: "default",
    numDot: "default",
    desc: "default",
    stack: "default",
    corner: "default",
    pcard: "default",
    pFeature: "compact",
    pFeatureCard: "compact",
  },
  terminal: {
    username: "compact",
    url: "compact",
    body: "compact",
  },
  services: {
    box: "compact",
    menuright: "compact",
    step: "compact",
    num: "compact",
    label: "default",
    desc: "default",
    menugrid: "compact",
    flagwrapper: "compact",
    flagarrow: "compact",
  },
  term: {
    box: "compact",
    terms: "compact",
    items: "compact",
  },
  clients: {
    box: "compact",
    cc: "compact",
    industry: "compact",
    result: "compact",
    label: "compact",
    tcard: "compact",
    quote: "compact",
    avatar: "compact",
    name: "compact",
    role: "compact",
    timeline: "compact",
    tlItem: "compact",
    tlDot: "compact",
    tlContent: "compact",
    tlLabel: "compact",
  },
  contact: {
    big: "default",
    sub: "compact",
    link: "compact",
  },
  hiddens: "hidden",
  footer: {
    box: "compact",
    label: "compact",
  },
};
