export const mobileshort = {
  navbar: {
    nav: "nav-short",
    displayText: "hidden",
    displayImage: "static top-0",
    logoImage: "logo-image-short",
    hamburger: " hamburger-short",
    heroCTA: "heroCTAShort",
    menu: "mt-4",
  },
  hero: {
    box: "hero-box-short",
    title: "hero-title-short",
    eyebrow: "hero-eyebrow-short",
    subtitle: "hero-subtitle-short",
    desc: "hero-desc-short ",
    rustBadge: "rust-badge-short",
    scrollHint: "scrollHintShort",
    right: "hidden",
    last: "text-[clamp(4.5rem,9vw,7.5rem)] tracking-[-0.02em] -mt-8",
    topdots: "top-4 right-8 w-55 h-37.5",
    bottomdots: "bottom-45 right-8 w-55 h-37.5",
    centerDots: "right-10 top-1/3",
  },
  section: {
    wrapper: "wrapperShort",
    about: "sectionAboutShort",
    skill: "bg-surface sectionSkillShort",
    service: "compact",
    client: "compact px-2",
  },
  button: {
    buttonCta: "py-2",
    buttonHero:
      "py-2 px-[clamp(0.5rem,calc(-1rem+10vw),1rem)] text-[clamp(0.625rem,calc(0.25rem+2.5vw),0.75rem)]",
  },
  about: {
    grid: "about-grid-short",
    photoWrap: "about-photo-wrap-short",
    photoFrame: "about-photo-frame-short",
    content: "mb-3",
    factBox: "about-facts-short",
    factIcons: "about-fact-icon-short",
  },
  standard: {
    eyebrow: "eyebrow-short",
    header: "title-short",
    desc: "desc-short",
    icon: "short",
    stack: "short",
  },
  stats: {
    box: "grid-cols-2 p-2 grid gap-2",
    stat: "min-w-full borderR rounded-xl shadow-2xl p-1 overflow transition-surface hover:borderY",
    glow: "-bottom-5 -right-2.5 w-15 h-10 rounded-1/2 blur-[25px] opacity-[0.15] bg-teal",
    num: "font-mono text-[clamp(0.75rem,calc(0.245rem+2.516vw),1rem)] font-bold text-text leading-none mb-[0.4rem]",
    label:
      "text-[clamp(0.75rem,calc(0.245rem+2.516vw),1rem)] text-muted uppercase tracking-[0.06em]",
  },
  skill: {
    box: "grid-cols-1 gap-4 border-0! bg-transparent! grid px-px ",
    card: "short beam beam-rust",
  },
  experience: {
    items: "compact",
    expdate: "short",
    company: "title-short",
    desc: "desc-short",
    divider: "my-1",
  },
  project: {
    num: "default",
    numDot: "default",
    desc: "default",
    stack: "default",
    corner: "default",
    pcard: "default",
    pFeature: "compact",
    pFeatureCard: "compact",
  },
  terminal: {
    username: "compact",
    url: "compact",
    body: "compact",
  },
  services: {
    box: "compact",
    menuright: "compact",
    step: "compact",
    num: "compact",
    label: "default",
    desc: "default",
    menugrid: "compact",
    flagwrapper: "compact",
    flagarrow: "compact",
  },
  term: {
    box: "compact",
    terms: "compact",
    items: "compact",
  },
   clients:{
    box:"compact",
     cc:"compact",
    industry:"compact"
  },
  hiddens: "hidden",
};
