export const mobilenormal={
    hero: {
    box: "short",
    eyebrow: "short",
    title: "short",
    first: "short",
    last: "short",
    heroCTA: "heroCTAShort",
    subtitle: "short",
    scrollHint: "scrollHintShort",
    stackBar: "hidden",
    stackItem: "short",
    stackIcon: "hidden",
    stackName: "hidden",
    right: "hidden",
    orb: "hidden",
    ring: "hidden",
    ring2: "hidden",
    termCardBack: "hidden",
    termCardBackLeft: "hidden",
    termCard: "hidden",
    topdots: "hidden",
    bottomdots: "hidden",
    centerDots: "hidden",
    planet: "hidden",
    planetRing: "hidden",
    orbit: "hidden",
  },
  navbar: {
    nav: "compact",
    displayText: "hidden",
    NavLinkS: "flex justify-center items-center gap-4",
    displayImage: "static top-0",
    menuEyeBrow: "text-xs3",
    logoImage: "logo-image-short",
    menu: "mt-4",
    hamburger: " hamburger-short",
    logoTextImage: "w-10 h-10",
    logoText: "text-[clamp(1rem,calc(-2.012rem+6.275vw),2rem)]",
    navLink: "",
  },
  button: {
    primary: "px-6 py-3 rounded-xl",
    buttonCta: "py-[0.85rem]",
  },
  section: {
    wrapper: "h-screen inline-table",
    default: "short",
    about: "short",
    client: "py-24 px-[48px]",
    skill: "short",
    contact: "",
  },
  about: {
    left: "short",
    illustration: "short",
    top: "shorttop",
    bottom: "shortbottom",
    card: "short",
  },
  hiddens: "",
  standard: {
    header: "section-text-header-short",
    desc: "section-subtitle",
    icon: "text-[1.4rem] mb-4",
    stack: "",
    slide: "compact",
    viewport: "compact",
    ferris: "short",
    timelineSubtitle: "compact",
    containercustom: "compact",
  },
  stats: {
    box: "short",
  },
  skill: {
    box: "short",
    techCard: "short",
  },
  project: {
    box: "short",
    pFeature: "short",
    pFeatureCard: "short",
    portfoliolist: "",
  },
  experience: {
    divider: "",
  },
  services: {
    menugrid:"compact",
    sTitle:"short",
    sDesc:"short",
    sLi:"short",
    sPrice:"short",
    sPriceLabel:"short",
    sPriceValue:"short",

  },
  footer: {
    box: "compact",
    label: "compact",
  },
}