import {
  base,
  desktop1024Short,
  desktop1280,
  desktop1280V1,
  mobilenormal,
  mobileshort,
  mobileTallV1,
  mobileTall,
  tabShortV1,
  tabShort,
  tabNormal,
} from "./devices/index";
export const theme = {
  base:base,
  "mobile-short": mobileshort,
  "mobile-normal": mobilenormal,
  "mobile-tall-v1": mobileTallV1,
  "mobile-tall": mobileTall,
  "tablet-short-v1":tabShortV1,
  "tablet-short":tabShort,
  "tablet-normal":tabNormal,
  "desktop-1024-short":desktop1024Short, 
  "desktop-1280":desktop1280, 
  "desktop-1280-v1":desktop1280V1, 
};
